colourful: true

filekinds:
  normal:          { foreground: "#c6c6c6" }  
  directory:       { foreground: "#ffffff" }  
  symlink:         { foreground: "#dde1e6" }   
  pipe:            { foreground: "#c6c6c6" }   
  block_device:    { foreground: "#a8a8a8" }   
  char_device:     { foreground: "#a8a8a8" }
  socket:          { foreground: "#8d8d8d" }   
  special:         { foreground: "#8d8d8d" }
  executable:      { foreground: "#ffffff", is_bold: true } 
  mount_point:     { foreground: "#a8a8a8" }

perms:
  user_read:         { foreground: "#dde1e6", is_bold: true }
  user_write:        { foreground: "#c6c6c6", is_bold: true }
  user_execute_file: { foreground: "#ffffff", is_bold: true }
  user_execute_other: { foreground: "#ffffff", is_bold: true }
  group_read:        { foreground: "#c6c6c6" }
  group_write:       { foreground: "#dde1e6" }
  group_execute:     { foreground: "#ffffff" }
  other_read:        { foreground: "#c6c6c6" }
  other_write:       { foreground: "#dde1e6" }
  other_execute:     { foreground: "#ffffff" }
  special_user_file: { foreground: "#c6c6c6" }
  special_other:     { foreground: "#8d8d8d" }
  attribute:         { foreground: "#8d8d8d" }

size:
  major:        { foreground: "#c6c6c6" }
  minor:        { foreground: "#a8a8a8" }
  number_byte:  { foreground: "#ffffff" }
  number_kilo:  { foreground: "#f2f4f8" }
  number_mega:  { foreground: "#dde1e6" }
  number_giga:  { foreground: "#c6c6c6" }
  number_huge:  { foreground: "#a8a8a8" }
  unit_byte:    { foreground: "#dde1e6" }
  unit_kilo:    { foreground: "#c6c6c6" }
  unit_mega:    { foreground: "#a8a8a8" }
  unit_giga:    { foreground: "#8d8d8d" }
  unit_huge:    { foreground: "#6f6f6f" }

users:
  user_you:     { foreground: "#ffffff" }
  user_root:    { foreground: "#f2f4f8" }
  user_other:   { foreground: "#dde1e6" }
  group_yours:  { foreground: "#c6c6c6" }
  group_other:  { foreground: "#8d8d8d" }
  group_root:   { foreground: "#a8a8a8" }

links:
  normal:           { foreground: "#dde1e6" }
  multi_link_file:  { foreground: "#dde1e6" }

git:
  new:         { foreground: "#ffffff" }
  modified:    { foreground: "#f2f4f8" }
  deleted:     { foreground: "#8d8d8d" }
  renamed:     { foreground: "#c6c6c6" }
  typechange:  { foreground: "#a8a8a8" }
  ignored:     { foreground: "#8d8d8d" }
  conflicted:  { foreground: "#6f6f6f" }

git_repo:
  branch_main: { foreground: "#c6c6c6" }
  branch_other: { foreground: "#a8a8a8" }
  git_clean:   { foreground: "#ffffff" }
  git_dirty:   { foreground: "#8d8d8d" }

security_context:
  colon:       { foreground: "#8d8d8d" }
  user:        { foreground: "#8d8d8d" }
  role:        { foreground: "#c6c6c6" }
  typ:         { foreground: "#6f6f6f" }
  range:       { foreground: "#c6c6c6" }

file_type:
  image:       { foreground: "#f2f4f8" }
  video:       { foreground: "#dde1e6" }
  music:       { foreground: "#ffffff" }
  lossless:    { foreground: "#c6c6c6" }
  crypto:      { foreground: "#8d8d8d" }
  document:    { foreground: "#f2f4f8" }
  compressed:  { foreground: "#c6c6c6" }
  temp:        { foreground: "#8d8d8d" }
  compiled:    { foreground: "#c6c6c6" }
  source:      { foreground: "#dde1e6" }

punctuation:      { foreground: "#8d8d8d" }
date:             { foreground: "#c6c6c6" }
inode:            { foreground: "#a8a8a8" }
blocks:           { foreground: "#8d8d8d" }
header:           { foreground: "#ffffff" }
octal:            { foreground: "#8d8d8d" }
flags:            { foreground: "#c6c6c6" }

symlink_path:       { foreground: "#c6c6c6" }
control_char:       { foreground: "#c6c6c6" }
broken_symlink:     { foreground: "#6f6f6f" }
broken_path_overlay: { foreground: "#393939" }
